  - name: upgrade all packages
    yum: name=* state=latest

  - name: install centos-release-openstack-queens
    yum: name=centos-release-openstack-stein state=present
    when: ansible_distribution in ['RedHat', 'CentOS']

  - name: installing dependencies
    yum:
      name:
        - curl
        - gcc
        - memcached
        - rsync
        - sqlite
        - xfsprogs
        - git
        - git-core
        - libffi-devel
        - xinetd
        - python-devel
        - python-simplejson
        - pyxattr
        - python-eventlet
        - python-greenlet
        - python-netifaces
        - python-pip
        - python-dns
        - python-mock
        - tree
        - vim
        - make
        - autoconf
        - automake
        - libtool
        - openssl-devel
        - sysstat
        - redhat-rpm-config
        - rsyslog
        - redhat-lsb
        - libxml2-devel
        - libxslt-devel
      state: present

  - name: installing fedora only dependencies
    yum:
      name:
        - python2-libselinux
        - rsync-daemon
      state: present
    when: ansible_distribution in ['Fedora']

  - name: install golang
    yum:
      name:
        - golang
      state: present
    when: not build_golang

  - name: install python modules with pip
    pip:
      name:
        - tox
        - nose
        - xattr
        - git-review
        - coverage
        - Paste
        - pyudev
        - pip
        - setuptools
        - bindep
        - crudini
      state: latest

  - name: check if golang already installed
    stat: path=/usr/local/go
    register: golang_installed

  - name: install golang from binary
    become: true
    unarchive: src={{ golang_bin }} dest=/usr/local copy=no
    when: not golang_installed.stat.exists and build_golang

  - name: make sure PATH includes the go bin directory
    lineinfile: dest=/home/{{ username }}/.bashrc line="export PATH=${PATH}:/usr/local/go/bin"
    when: build_golang
