- name: installing dependencies
  package: name={{ item }} state=present
  with_items:
    - liberasurecode
    - liberasurecode-devel
    - python-pyeclib
  when: libec_rpm is not defined or not libec_rpm

- name: install specific libec rpm
  package: name={{ libec_rpm }}
  when: libec_rpm is defined and libec_rpm

- name: install specific pyeclib rpm
  package: name={{ pyeclib_rpm }}
  when: pyeclib_rpm is defined and pyeclib_rpm
